### PING 
GET http://localhost:8080/ping HTTP/1.1

### create a new todo item curl using form data
POST http://localhost:8080/add HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

title=test

### GET COMPLETED TODOS
GET http://localhost:8080/todo/completed HTTP/1.1
Accept: application/json

### GET INCOMPLETED TODOS
GET http://localhost:8080/todo/incomplete HTTP/1.1
Accept: application/json

### DELETE TODO WITH ID
DELETE http://localhost:8080/delete/1 HTTP/1.1

### UPDATE TODO WITH ID
PUT http://localhost:8080/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

status=true